// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5Xa1trfb9x5hVYQfbAL5mMyDz1Z4cNM',
    appId: '1:489085161994:web:51f919fb77f0b16a6d85f3',
    messagingSenderId: '489085161994',
    projectId: 'nextgen-hackathon',
    authDomain: 'nextgen-hackathon.firebaseapp.com',
    storageBucket: 'nextgen-hackathon.appspot.com',
    measurementId: 'G-N4QQG6PXY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAoa_Grt-JB9LtAyylJySTT03SVKiRz1g',
    appId: '1:489085161994:android:0e871305b59eefe56d85f3',
    messagingSenderId: '489085161994',
    projectId: 'nextgen-hackathon',
    storageBucket: 'nextgen-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMnqqiDgu3L--_mPjuTlduzoaLJm_DFoU',
    appId: '1:489085161994:ios:7adbfca8feb4c5756d85f3',
    messagingSenderId: '489085161994',
    projectId: 'nextgen-hackathon',
    storageBucket: 'nextgen-hackathon.appspot.com',
    iosClientId: '489085161994-boavojbbve0p8g1ts4rfv3nj5dtmp1eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextgenHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMnqqiDgu3L--_mPjuTlduzoaLJm_DFoU',
    appId: '1:489085161994:ios:f9c16becb03d271c6d85f3',
    messagingSenderId: '489085161994',
    projectId: 'nextgen-hackathon',
    storageBucket: 'nextgen-hackathon.appspot.com',
    iosClientId: '489085161994-tigdmr6292a12lg3a3o6hgl953acbfhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextgenHackathon.RunnerTests',
  );
}
